excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://lizahcarr.github.io
title: Content Marketing
tagline: Content is Fire, social media is Gasoline
description: Content Marketing is the backbone of communication and my tips to promote content will help you a lot. 
paginate: 5